###### Flight Service ######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-flightservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-flight-deployment
  template:
    metadata:
      labels:
        name: acmeair-flight-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
      - name: acmeair-flightservice-java
        image: acmeair-flightservice-java:latest
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: IfNotPresent
        env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: password
        - name: MONGO_HOST
          value: acmeair-flight-db
        - name: SECURE_SERVICE_CALLS
          value: 'true'
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-flight-service
spec:
  ports:
    - port: 9080
  selector:
    name: acmeair-flight-deployment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/connection-proxy-header: "keep-alive"
  name: acmeair-flight-ingress
spec:
  rules:
  - host:
    http:
      paths:
      - pathType: Prefix
        path: /flight
        backend:
          service: 
            name: acmeair-flight-service
            port: 
              number: 9080
